### ISSUE TITLE
Could not find protocbridge.forntend.BridgeApp  only on Windows. Works on Linux. ver 0.99.18

### ISSUE THREAD

**Issue by mikolajs** [thesamet/sbt-protoc#72]
Newer versions that don't use python produce error on Windows (10): 

`Error: Could not find or load main class protocbridge.frontend.BridgeApp
--scala_out: protoc-gen-scala: Plugin failed with status code 1.
[trace] Stack trace suppressed: run last compile:protocGenerate for the full output.
[error] (compile:protocGenerate) protoc returned exit code: 1`

`java.lang.RuntimeException: protoc returned exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.scala:142)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.sbtprotoc$ProtocPlugin$$anonfun$$compileProto$1(ProtocPlugin.scala:175)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$5.apply(ProtocPlugin.scala:186)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$5.apply(ProtocPlugin.scala:185)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:192)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:167)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (compile:protocGenerate) protoc returned exit code: 1`

**Comment by thesamet** [comment]
Can you provide additional details? JDK version, does it help on a clean project? You can try `sbt new scalapb/scalapb-template.g8` to quickly create a minimal project.

**Comment by mikolajs** [comment]
Hi, 
I have the same problem with new created project from template.
The output is:
 Compiling 1 protobuf files to C:\Users\Public\IdeaProjects\testjavaprotobuf\target\scala-2.12\src_managed\main,C:\Users\Public\IdeaProjects\testjavaprotobuf\target\scala-2.12\src_managed\main
[info] Compiling schema C:\Users\Public\IdeaProjects\testjavaprotobuf\src\main\protobuf\proto2.proto
protoc-jar: protoc version: 3.5.1, detected platform: windows-x86_64 (windows 10/amd64)
protoc-jar: embedded: bin/3.5.1/protoc-3.5.1-windows-x86_64.exe
protoc-jar: executing: [C:\Users\MIKOAJ~1\AppData\Local\Temp\protocjar4514364793790410785\bin\protoc.exe, --plugin=protoc-gen-scala=C:\Users\MIKOAJ~1\AppData\Local\Temp\protocbridge8290119658191321465.bat, --java_out=:C:\Users\Public\IdeaProjects\testjavaprotobuf\target\scala-2.12\src_managed\main, --scala_out=java_conversions,grpc:C:\Users\Public\IdeaProjects\testjavaprotobuf\target\scala-2.12\src_managed\main, -IC:\Users\Public\IdeaProjects\testjavaprotobuf\src\main\protobuf, -IC:\Users\Public\IdeaProjects\testjavaprotobuf\target\protobuf_external, -IC:\Users\Public\IdeaProjects\testjavaprotobuf\src\main\protobuf, -IC:\Users\Public\IdeaProjects\testjavaprotobuf\target\protobuf_external, C:\Users\Public\IdeaProjects\testjavaprotobuf\src\main\protobuf\proto2.proto]
Error: Could not find or load main class protocbridge.frontend.BridgeApp
--scala_out: protoc-gen-scala: Plugin failed with status code 1.
[error] java.lang.RuntimeException: protoc returned exit code: 1
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:142)
[error]         at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:182)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:186)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$1(ProtocPlugin.scala:192)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
sbt:testJavaProtobuf> [error] (Compile / protocGenerate) protoc returned exit code: 1
[error] Total time: 22 s, completed 2018-09-24 08:51:04

I wonder if the problem is caused by polish letters in my home directory name. 
Thanks for your time.

**Comment by lodo1995** [comment]
Any news on this? I have the exact same issue. I'm on Windows 10, with scala 2.12, using version 0.99.15 of this plugin. I don't have strange letters in my home directory, but I have a space.

I noticed that both in my case and @mikolajs case, the home directory path gets shortened using windows tilde syntax (8.3 compatibiliy format). I don't know if that might be related.

**Comment by thesamet** [comment]
I wasn't able to reproduce it the last time I tried on a windows VM I installed. Will you be able to debug this yourself and provide a PR? Maybe try running the tests locally, and inspect why the JVM that we launch is unable to see the class we are passing it.

**Comment by thesamet** [comment]
Alternatively, if you can provide somehow access to a Windows machine (or a virtual box) that can demonstrate this problem, I'll be happy to look into this.

**Comment by lodo1995** [comment]
@thesamet  Ah, my fault!
I was using an old version of `sbt-protoc`. This issue has been fixed somewhere between `0.99.17` and `0.99.18`.

**Comment by lodo1995** [comment]
I think it was fixed by this: https://github.com/scalapb/protoc-bridge/pull/17

**Comment by thesamet** [comment]
Glad to know it's working.

The issue mentions 0.99.18 so I wonder if @mikolajs still experiences this. I haven't received other reports of this bug, so I assume it is an isolated problem. I will close this now. If anyone observes this problem in the future, please file a new bug.

**Comment by throuch** [comment]
I use plugin version 0.99.19 and I reproduced the problem under Windows 10. The problem doesn't occur under Linux.

**Comment by thesamet** [comment]
@throuch can you file a new issue with exact instructions on how to reproduce? Also, can you use the latest version of this plugin?

**Comment by throuch** [comment]
Yes I found the cause of the problem as suggested by other users. It comes from unsupported characters in the user path.
My windows user was "Développeur" and it failed. When I switch to another user with the exact same project, it worked.

**Comment by thesamet** [comment]
pr to add support for all characters possible in a path will be welcome.
